import { cookies } from 'next/headers'
import '../../globals.css'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const token = cookies().get('token')
    if (!token) return redirect('/user/login')
    const result = await axios.get(`http://127.0.0.1:8000/api/auth/user/`,{
        headers: {
            'Authorization': `Token ${token.value}`
        }
    })
    if (!result) return redirect('/user/login')

  return (
    <>
            {children}

    </>

  )
}
